// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"fmt"
	"net/http"
	"strings"

	"Water-Level-Gauge-er/orchestrator/restapi/operations/configuration"
	"Water-Level-Gauge-er/orchestrator/restapi/operations/water_level"
	"Water-Level-Gauge-er/orchestrator/restapi/operations/water_level_anomaly"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/cmdutils"
)

// NewOrchestratorAPI creates a new Orchestrator instance
func NewOrchestratorAPI(spec *loads.Document) *OrchestratorAPI {
	return &OrchestratorAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		ConfigurationGetConfigurationHandler: configuration.GetConfigurationHandlerFunc(func(params configuration.GetConfigurationParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation configuration.GetConfiguration has not yet been implemented")
		}),

		WaterLevelAnomalyGetWaterAnomalyHandler: water_level_anomaly.GetWaterAnomalyHandlerFunc(func(params water_level_anomaly.GetWaterAnomalyParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation water_level_anomaly.GetWaterAnomaly has not yet been implemented")
		}),

		WaterLevelAnomalyGetWaterAnomalyHistoryHandler: water_level_anomaly.GetWaterAnomalyHistoryHandlerFunc(func(params water_level_anomaly.GetWaterAnomalyHistoryParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation water_level_anomaly.GetWaterAnomalyHistory has not yet been implemented")
		}),

		WaterLevelGetWaterLevelHistoryHandler: water_level.GetWaterLevelHistoryHandlerFunc(func(params water_level.GetWaterLevelHistoryParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation water_level.GetWaterLevelHistory has not yet been implemented")
		}),

		ConfigurationPostConfigurationHandler: configuration.PostConfigurationHandlerFunc(func(params configuration.PostConfigurationParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation configuration.PostConfiguration has not yet been implemented")
		}),

		WaterLevelGetWaterLevelHandler: water_level.GetWaterLevelHandlerFunc(func(params water_level.GetWaterLevelParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation water_level.GetWaterLevel has not yet been implemented")
		}),

		WaterLevelSaveWaterLevelHandler: water_level.SaveWaterLevelHandlerFunc(func(params water_level.SaveWaterLevelParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation water_level.SaveWaterLevel has not yet been implemented")
		}),
	}
}

/*OrchestratorAPI This is specification for water level gauge central service. It has several APIs designed for supplying data to frontend as well as backend APIs for devices to communicate with it. */
type OrchestratorAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// ConfigurationGetConfigurationHandler sets the operation handler for the get configuration operation
	ConfigurationGetConfigurationHandler configuration.GetConfigurationHandler
	// WaterLevelAnomalyGetWaterAnomalyHandler sets the operation handler for the get water anomaly operation
	WaterLevelAnomalyGetWaterAnomalyHandler water_level_anomaly.GetWaterAnomalyHandler
	// WaterLevelAnomalyGetWaterAnomalyHistoryHandler sets the operation handler for the get water anomaly history operation
	WaterLevelAnomalyGetWaterAnomalyHistoryHandler water_level_anomaly.GetWaterAnomalyHistoryHandler
	// WaterLevelGetWaterLevelHistoryHandler sets the operation handler for the get water level history operation
	WaterLevelGetWaterLevelHistoryHandler water_level.GetWaterLevelHistoryHandler
	// ConfigurationPostConfigurationHandler sets the operation handler for the post configuration operation
	ConfigurationPostConfigurationHandler configuration.PostConfigurationHandler
	// WaterLevelGetWaterLevelHandler sets the operation handler for the get water level operation
	WaterLevelGetWaterLevelHandler water_level.GetWaterLevelHandler
	// WaterLevelSaveWaterLevelHandler sets the operation handler for the save water level operation
	WaterLevelSaveWaterLevelHandler water_level.SaveWaterLevelHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []cmdutils.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...any)
}

// UseRedoc for documentation at /docs
func (o *OrchestratorAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *OrchestratorAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *OrchestratorAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *OrchestratorAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *OrchestratorAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *OrchestratorAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *OrchestratorAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *OrchestratorAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *OrchestratorAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the OrchestratorAPI
func (o *OrchestratorAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ConfigurationGetConfigurationHandler == nil {
		unregistered = append(unregistered, "configuration.GetConfigurationHandler")
	}
	if o.WaterLevelAnomalyGetWaterAnomalyHandler == nil {
		unregistered = append(unregistered, "water_level_anomaly.GetWaterAnomalyHandler")
	}
	if o.WaterLevelAnomalyGetWaterAnomalyHistoryHandler == nil {
		unregistered = append(unregistered, "water_level_anomaly.GetWaterAnomalyHistoryHandler")
	}
	if o.WaterLevelGetWaterLevelHistoryHandler == nil {
		unregistered = append(unregistered, "water_level.GetWaterLevelHistoryHandler")
	}
	if o.ConfigurationPostConfigurationHandler == nil {
		unregistered = append(unregistered, "configuration.PostConfigurationHandler")
	}
	if o.WaterLevelGetWaterLevelHandler == nil {
		unregistered = append(unregistered, "water_level.GetWaterLevelHandler")
	}
	if o.WaterLevelSaveWaterLevelHandler == nil {
		unregistered = append(unregistered, "water_level.SaveWaterLevelHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *OrchestratorAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *OrchestratorAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *OrchestratorAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
//
// MIME type parameters are ignored here.
func (o *OrchestratorAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		if mt == "application/json" {
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}

	return result
}

// ProducersFor gets the producers for the specified media types.
//
// MIME type parameters are ignored here.
func (o *OrchestratorAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		if mt == "application/json" {
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}

	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *OrchestratorAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the orchestrator API
func (o *OrchestratorAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *OrchestratorAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/configuration"] = configuration.NewGetConfiguration(o.context, o.ConfigurationGetConfigurationHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/water/anomaly"] = water_level_anomaly.NewGetWaterAnomaly(o.context, o.WaterLevelAnomalyGetWaterAnomalyHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/water/anomaly/history"] = water_level_anomaly.NewGetWaterAnomalyHistory(o.context, o.WaterLevelAnomalyGetWaterAnomalyHistoryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/water/level/history"] = water_level.NewGetWaterLevelHistory(o.context, o.WaterLevelGetWaterLevelHistoryHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/configuration"] = configuration.NewPostConfiguration(o.context, o.ConfigurationPostConfigurationHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/water/level"] = water_level.NewGetWaterLevel(o.context, o.WaterLevelGetWaterLevelHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/water/level"] = water_level.NewSaveWaterLevel(o.context, o.WaterLevelSaveWaterLevelHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *OrchestratorAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *OrchestratorAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *OrchestratorAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *OrchestratorAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *OrchestratorAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
