// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger Water Level Gauge-er 2.0
//
//	This is specification for water level gauge central service. It has several APIs designed for supplying data to frontend as well as backend APIs for devices to communicate with it.
//	Schemes:
//	  http
//	Host: gauger.orchestrator.swagger.io
//	BasePath: /api
//	Version: 1.0.0
//	License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: <spulkit489@gmail.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
