// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is specification for water level gauge central service. It has several APIs designed for supplying data to frontend as well as backend APIs for devices to communicate with it.",
    "title": "Swagger Water Level Gauge-er 2.0",
    "contact": {
      "email": "spulkit489@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "gauger.orchestrator.swagger.io",
  "basePath": "/api",
  "paths": {
    "/configuration": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Configuration"
        ],
        "summary": "Retrieve static configuration",
        "responses": {
          "200": {
            "description": "Configuration fetched successfully",
            "schema": {
              "$ref": "#/definitions/Configuration"
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Configuration"
        ],
        "summary": "Store static configuration",
        "parameters": [
          {
            "name": "Configuration",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Configuration"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Configuration stored successfully"
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/anomaly": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level Anomaly"
        ],
        "responses": {
          "200": {
            "description": "Fetched Water Anomaly successfully",
            "schema": {
              "$ref": "#/definitions/WaterLevelAnomaly"
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/anomaly/history": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level Anomaly"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/PageNumber"
          },
          {
            "$ref": "#/parameters/ItemsPerPage"
          }
        ],
        "responses": {
          "200": {
            "description": "Fetched Water Anomaly History successfully",
            "schema": {
              "type": "object",
              "properties": {
                "Entries": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/WaterLevelAnomaly"
                  }
                },
                "TotalEntries": {
                  "description": "total number of entries, for pagination",
                  "type": "integer"
                }
              }
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/level": {
      "get": {
        "description": "Retrieves the current water level of the tank, along with total tank capacity.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level"
        ],
        "operationId": "getWaterLevel",
        "responses": {
          "200": {
            "description": "Retrived water level successfully",
            "schema": {
              "$ref": "#/definitions/WaterLevel"
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level"
        ],
        "summary": "Stores the current water level reading in the database.",
        "operationId": "saveWaterLevel",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "emptyWaterDepth": {
                  "description": "depth of empty volume in tank.",
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Current water level stored successfully."
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/level/history": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/PageNumber"
          },
          {
            "$ref": "#/parameters/ItemsPerPage"
          }
        ],
        "responses": {
          "200": {
            "description": "Water Level History successfully fetched",
            "schema": {
              "type": "object",
              "properties": {
                "Entries": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/WaterLevel"
                  }
                },
                "TotalEntries": {
                  "description": "total number of entries, for pagination",
                  "type": "integer"
                }
              }
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Configuration": {
      "type": "object",
      "properties": {
        "DeviceIP": {
          "description": "IP of gauging device, required in IOT mode",
          "type": "string",
          "pattern": "(\\b25[0-5]|\\b2[0-4][0-9]|\\b[01]?[0-9][0-9]?)(\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}"
        },
        "DevicePort": {
          "description": "Port on which gauging device is listening, required in IOT mode.",
          "type": "integer",
          "example": 31028
        },
        "WaterFlowThreshold": {
          "description": "water flow threshold in L/s, against which water flow anomaly is declared. If it is set to 0, that means anomaly detection is turned off.",
          "type": "integer"
        },
        "WaterTankDiameter": {
          "description": "Diameter of water tank (assumption is water tank is cylindrical) in cm.",
          "type": "integer",
          "example": 123
        },
        "WaterTankTotalVolume": {
          "description": "Total Volume of Water Tank in Litres.",
          "type": "integer",
          "example": 1000
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "description": "Error description in human understandable language",
          "type": "string"
        }
      }
    },
    "WaterLevel": {
      "type": "object",
      "properties": {
        "reportedAt": {
          "description": "when was last reading recorded.",
          "type": "string",
          "format": "date-time"
        },
        "totalVolume": {
          "description": "total volume of tank (in L)",
          "type": "integer"
        },
        "waterVolume": {
          "description": "total volume of water present (in L)",
          "type": "integer"
        }
      }
    },
    "WaterLevelAnomaly": {
      "type": "object",
      "properties": {
        "observedFlowRate": {
          "description": "observed flow rate in L/s",
          "type": "integer"
        },
        "reportedAt": {
          "description": "when was last reading recorded.",
          "type": "string",
          "format": "date-time"
        },
        "thresholdFlowRate": {
          "description": "threshold flow rate in L/s",
          "type": "integer"
        }
      }
    }
  },
  "parameters": {
    "ItemsPerPage": {
      "type": "integer",
      "default": 0,
      "description": "items per page to be fetched",
      "name": "itemsPerPage",
      "in": "query"
    },
    "PageNumber": {
      "type": "integer",
      "default": 0,
      "description": "page number to be fetched",
      "name": "pageNumber",
      "in": "query"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is specification for water level gauge central service. It has several APIs designed for supplying data to frontend as well as backend APIs for devices to communicate with it.",
    "title": "Swagger Water Level Gauge-er 2.0",
    "contact": {
      "email": "spulkit489@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "gauger.orchestrator.swagger.io",
  "basePath": "/api",
  "paths": {
    "/configuration": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Configuration"
        ],
        "summary": "Retrieve static configuration",
        "responses": {
          "200": {
            "description": "Configuration fetched successfully",
            "schema": {
              "$ref": "#/definitions/Configuration"
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Configuration"
        ],
        "summary": "Store static configuration",
        "parameters": [
          {
            "name": "Configuration",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Configuration"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Configuration stored successfully"
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/anomaly": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level Anomaly"
        ],
        "responses": {
          "200": {
            "description": "Fetched Water Anomaly successfully",
            "schema": {
              "$ref": "#/definitions/WaterLevelAnomaly"
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/anomaly/history": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level Anomaly"
        ],
        "parameters": [
          {
            "type": "integer",
            "default": 0,
            "description": "page number to be fetched",
            "name": "pageNumber",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "items per page to be fetched",
            "name": "itemsPerPage",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Fetched Water Anomaly History successfully",
            "schema": {
              "type": "object",
              "properties": {
                "Entries": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/WaterLevelAnomaly"
                  }
                },
                "TotalEntries": {
                  "description": "total number of entries, for pagination",
                  "type": "integer"
                }
              }
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/level": {
      "get": {
        "description": "Retrieves the current water level of the tank, along with total tank capacity.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level"
        ],
        "operationId": "getWaterLevel",
        "responses": {
          "200": {
            "description": "Retrived water level successfully",
            "schema": {
              "$ref": "#/definitions/WaterLevel"
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level"
        ],
        "summary": "Stores the current water level reading in the database.",
        "operationId": "saveWaterLevel",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "emptyWaterDepth": {
                  "description": "depth of empty volume in tank.",
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Current water level stored successfully."
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/water/level/history": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Water Level"
        ],
        "parameters": [
          {
            "type": "integer",
            "default": 0,
            "description": "page number to be fetched",
            "name": "pageNumber",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "items per page to be fetched",
            "name": "itemsPerPage",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Water Level History successfully fetched",
            "schema": {
              "type": "object",
              "properties": {
                "Entries": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/WaterLevel"
                  }
                },
                "TotalEntries": {
                  "description": "total number of entries, for pagination",
                  "type": "integer"
                }
              }
            }
          },
          "default": {
            "description": "Error encountered",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Configuration": {
      "type": "object",
      "properties": {
        "DeviceIP": {
          "description": "IP of gauging device, required in IOT mode",
          "type": "string",
          "pattern": "(\\b25[0-5]|\\b2[0-4][0-9]|\\b[01]?[0-9][0-9]?)(\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}"
        },
        "DevicePort": {
          "description": "Port on which gauging device is listening, required in IOT mode.",
          "type": "integer",
          "example": 31028
        },
        "WaterFlowThreshold": {
          "description": "water flow threshold in L/s, against which water flow anomaly is declared. If it is set to 0, that means anomaly detection is turned off.",
          "type": "integer"
        },
        "WaterTankDiameter": {
          "description": "Diameter of water tank (assumption is water tank is cylindrical) in cm.",
          "type": "integer",
          "example": 123
        },
        "WaterTankTotalVolume": {
          "description": "Total Volume of Water Tank in Litres.",
          "type": "integer",
          "example": 1000
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "description": "Error description in human understandable language",
          "type": "string"
        }
      }
    },
    "WaterLevel": {
      "type": "object",
      "properties": {
        "reportedAt": {
          "description": "when was last reading recorded.",
          "type": "string",
          "format": "date-time"
        },
        "totalVolume": {
          "description": "total volume of tank (in L)",
          "type": "integer"
        },
        "waterVolume": {
          "description": "total volume of water present (in L)",
          "type": "integer"
        }
      }
    },
    "WaterLevelAnomaly": {
      "type": "object",
      "properties": {
        "observedFlowRate": {
          "description": "observed flow rate in L/s",
          "type": "integer"
        },
        "reportedAt": {
          "description": "when was last reading recorded.",
          "type": "string",
          "format": "date-time"
        },
        "thresholdFlowRate": {
          "description": "threshold flow rate in L/s",
          "type": "integer"
        }
      }
    }
  },
  "parameters": {
    "ItemsPerPage": {
      "type": "integer",
      "default": 0,
      "description": "items per page to be fetched",
      "name": "itemsPerPage",
      "in": "query"
    },
    "PageNumber": {
      "type": "integer",
      "default": 0,
      "description": "page number to be fetched",
      "name": "pageNumber",
      "in": "query"
    }
  }
}`))
}
