// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Configuration configuration
//
// swagger:model Configuration
type Configuration struct {

	// IP of gauging device, required in IOT mode
	// Pattern: (\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}
	DeviceIP string `json:"DeviceIP,omitempty"`

	// Port on which gauging device is listening, required in IOT mode.
	// Example: 31028
	DevicePort int64 `json:"DevicePort,omitempty"`

	// water flow threshold in L/s, against which water flow anomaly is declared. If it is set to 0, that means anomaly detection is turned off.
	WaterFlowThreshold int64 `json:"WaterFlowThreshold,omitempty"`

	// Diameter of water tank (assumption is water tank is cylindrical) in cm.
	// Example: 123
	WaterTankDiameter int64 `json:"WaterTankDiameter,omitempty"`

	// Total Volume of Water Tank in Litres.
	// Example: 1000
	WaterTankTotalVolume int64 `json:"WaterTankTotalVolume,omitempty"`
}

// Validate validates this configuration
func (m *Configuration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configuration) validateDeviceIP(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DeviceIP) { // not required
		return nil
	}

	if err := validate.Pattern("DeviceIP", "body", m.DeviceIP, `(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this configuration based on context it is used
func (m *Configuration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Configuration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Configuration) UnmarshalBinary(b []byte) error {
	var res Configuration
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
