// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// WaterLevelAnomaly water level anomaly
//
// swagger:model WaterLevelAnomaly
type WaterLevelAnomaly struct {

	// observed flow rate in L/s
	ObservedFlowRate int64 `json:"observedFlowRate,omitempty"`

	// when was last reading recorded.
	// Format: date-time
	ReportedAt strfmt.DateTime `json:"reportedAt,omitempty"`

	// threshold flow rate in L/s
	ThresholdFlowRate int64 `json:"thresholdFlowRate,omitempty"`
}

// Validate validates this water level anomaly
func (m *WaterLevelAnomaly) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReportedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WaterLevelAnomaly) validateReportedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ReportedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("reportedAt", "body", "date-time", m.ReportedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this water level anomaly based on context it is used
func (m *WaterLevelAnomaly) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WaterLevelAnomaly) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WaterLevelAnomaly) UnmarshalBinary(b []byte) error {
	var res WaterLevelAnomaly
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
