// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// WaterLevel water level
//
// swagger:model WaterLevel
type WaterLevel struct {

	// when was last reading recorded.
	// Format: date-time
	ReportedAt strfmt.DateTime `json:"reportedAt,omitempty"`

	// total volume of tank (in L)
	TotalVolume int64 `json:"totalVolume,omitempty"`

	// total volume of water present (in L)
	WaterVolume int64 `json:"waterVolume,omitempty"`
}

// Validate validates this water level
func (m *WaterLevel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReportedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WaterLevel) validateReportedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ReportedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("reportedAt", "body", "date-time", m.ReportedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this water level based on context it is used
func (m *WaterLevel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WaterLevel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WaterLevel) UnmarshalBinary(b []byte) error {
	var res WaterLevel
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
