// Code generated by go-swagger; DO NOT EDIT.

package water_level

import (
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/runtime"
)

// GetWaterLevelHistoryOKCode is the HTTP code returned for type GetWaterLevelHistoryOK
const GetWaterLevelHistoryOKCode int = 200

/*
GetWaterLevelHistoryOK Water Level History successfully fetched

swagger:response getWaterLevelHistoryOK
*/
type GetWaterLevelHistoryOK struct {

	/*
	  In: Body
	*/
	Payload *GetWaterLevelHistoryOKBody `json:"body,omitempty"`
}

// NewGetWaterLevelHistoryOK creates GetWaterLevelHistoryOK with default headers values
func NewGetWaterLevelHistoryOK() *GetWaterLevelHistoryOK {

	return &GetWaterLevelHistoryOK{}
}

// WithPayload adds the payload to the get water level history o k response
func (o *GetWaterLevelHistoryOK) WithPayload(payload *GetWaterLevelHistoryOKBody) *GetWaterLevelHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water level history o k response
func (o *GetWaterLevelHistoryOK) SetPayload(payload *GetWaterLevelHistoryOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterLevelHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetWaterLevelHistoryDefault Error encountered

swagger:response getWaterLevelHistoryDefault
*/
type GetWaterLevelHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetWaterLevelHistoryDefault creates GetWaterLevelHistoryDefault with default headers values
func NewGetWaterLevelHistoryDefault(code int) *GetWaterLevelHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWaterLevelHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get water level history default response
func (o *GetWaterLevelHistoryDefault) WithStatusCode(code int) *GetWaterLevelHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get water level history default response
func (o *GetWaterLevelHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get water level history default response
func (o *GetWaterLevelHistoryDefault) WithPayload(payload *models.Error) *GetWaterLevelHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water level history default response
func (o *GetWaterLevelHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterLevelHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
