// Code generated by go-swagger; DO NOT EDIT.

package water_level

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetWaterLevelHandlerFunc turns a function with the right signature into a get water level handler
type GetWaterLevelHandlerFunc func(GetWaterLevelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWaterLevelHandlerFunc) Handle(params GetWaterLevelParams) middleware.Responder {
	return fn(params)
}

// GetWaterLevelHandler interface for that can handle valid get water level params
type GetWaterLevelHandler interface {
	Handle(GetWaterLevelParams) middleware.Responder
}

// NewGetWaterLevel creates a new http.Handler for the get water level operation
func NewGetWaterLevel(ctx *middleware.Context, handler GetWaterLevelHandler) *GetWaterLevel {
	return &GetWaterLevel{Context: ctx, Handler: handler}
}

/*
	GetWaterLevel swagger:route GET /water/level Water Level getWaterLevel

Retrieves the current water level of the tank, along with total tank capacity.
*/
type GetWaterLevel struct {
	Context *middleware.Context
	Handler GetWaterLevelHandler
}

func (o *GetWaterLevel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetWaterLevelParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
