// Code generated by go-swagger; DO NOT EDIT.

package water_level

import (
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/runtime"
)

// GetWaterLevelOKCode is the HTTP code returned for type GetWaterLevelOK
const GetWaterLevelOKCode int = 200

/*
GetWaterLevelOK Retrived water level successfully

swagger:response getWaterLevelOK
*/
type GetWaterLevelOK struct {

	/*
	  In: Body
	*/
	Payload *models.WaterLevel `json:"body,omitempty"`
}

// NewGetWaterLevelOK creates GetWaterLevelOK with default headers values
func NewGetWaterLevelOK() *GetWaterLevelOK {

	return &GetWaterLevelOK{}
}

// WithPayload adds the payload to the get water level o k response
func (o *GetWaterLevelOK) WithPayload(payload *models.WaterLevel) *GetWaterLevelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water level o k response
func (o *GetWaterLevelOK) SetPayload(payload *models.WaterLevel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterLevelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetWaterLevelDefault Error encountered

swagger:response getWaterLevelDefault
*/
type GetWaterLevelDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetWaterLevelDefault creates GetWaterLevelDefault with default headers values
func NewGetWaterLevelDefault(code int) *GetWaterLevelDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWaterLevelDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get water level default response
func (o *GetWaterLevelDefault) WithStatusCode(code int) *GetWaterLevelDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get water level default response
func (o *GetWaterLevelDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get water level default response
func (o *GetWaterLevelDefault) WithPayload(payload *models.Error) *GetWaterLevelDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water level default response
func (o *GetWaterLevelDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterLevelDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
