// Code generated by go-swagger; DO NOT EDIT.

package water_level

import (
	"context"
	stderrors "errors"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"

	"Water-Level-Gauge-er/orchestrator/models"
)

// GetWaterLevelHistoryHandlerFunc turns a function with the right signature into a get water level history handler
type GetWaterLevelHistoryHandlerFunc func(GetWaterLevelHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWaterLevelHistoryHandlerFunc) Handle(params GetWaterLevelHistoryParams) middleware.Responder {
	return fn(params)
}

// GetWaterLevelHistoryHandler interface for that can handle valid get water level history params
type GetWaterLevelHistoryHandler interface {
	Handle(GetWaterLevelHistoryParams) middleware.Responder
}

// NewGetWaterLevelHistory creates a new http.Handler for the get water level history operation
func NewGetWaterLevelHistory(ctx *middleware.Context, handler GetWaterLevelHistoryHandler) *GetWaterLevelHistory {
	return &GetWaterLevelHistory{Context: ctx, Handler: handler}
}

/*
	GetWaterLevelHistory swagger:route GET /water/level/history Water Level getWaterLevelHistory

GetWaterLevelHistory get water level history API
*/
type GetWaterLevelHistory struct {
	Context *middleware.Context
	Handler GetWaterLevelHistoryHandler
}

func (o *GetWaterLevelHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetWaterLevelHistoryParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetWaterLevelHistoryOKBody get water level history o k body
//
// swagger:model GetWaterLevelHistoryOKBody
type GetWaterLevelHistoryOKBody struct {

	// entries
	Entries []*models.WaterLevel `json:"Entries"`

	// total number of entries, for pagination
	TotalEntries int64 `json:"TotalEntries,omitempty"`
}

// Validate validates this get water level history o k body
func (o *GetWaterLevelHistoryOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEntries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWaterLevelHistoryOKBody) validateEntries(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Entries) { // not required
		return nil
	}

	for i := 0; i < len(o.Entries); i++ {
		if typeutils.IsZero(o.Entries[i]) { // not required
			continue
		}

		if o.Entries[i] != nil {
			if err := o.Entries[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getWaterLevelHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getWaterLevelHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get water level history o k body based on the context it is used
func (o *GetWaterLevelHistoryOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateEntries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWaterLevelHistoryOKBody) contextValidateEntries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Entries); i++ {

		if o.Entries[i] != nil {

			if typeutils.IsZero(o.Entries[i]) { // not required
				return nil
			}

			if err := o.Entries[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getWaterLevelHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getWaterLevelHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWaterLevelHistoryOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWaterLevelHistoryOKBody) UnmarshalBinary(b []byte) error {
	var res GetWaterLevelHistoryOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
