// Code generated by go-swagger; DO NOT EDIT.

package water_level

import (
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/runtime"
)

// SaveWaterLevelOKCode is the HTTP code returned for type SaveWaterLevelOK
const SaveWaterLevelOKCode int = 200

/*
SaveWaterLevelOK Current water level stored successfully.

swagger:response saveWaterLevelOK
*/
type SaveWaterLevelOK struct {
}

// NewSaveWaterLevelOK creates SaveWaterLevelOK with default headers values
func NewSaveWaterLevelOK() *SaveWaterLevelOK {

	return &SaveWaterLevelOK{}
}

// WriteResponse to the client
func (o *SaveWaterLevelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
SaveWaterLevelDefault Error encountered

swagger:response saveWaterLevelDefault
*/
type SaveWaterLevelDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSaveWaterLevelDefault creates SaveWaterLevelDefault with default headers values
func NewSaveWaterLevelDefault(code int) *SaveWaterLevelDefault {
	if code <= 0 {
		code = 500
	}

	return &SaveWaterLevelDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the save water level default response
func (o *SaveWaterLevelDefault) WithStatusCode(code int) *SaveWaterLevelDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the save water level default response
func (o *SaveWaterLevelDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the save water level default response
func (o *SaveWaterLevelDefault) WithPayload(payload *models.Error) *SaveWaterLevelDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the save water level default response
func (o *SaveWaterLevelDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SaveWaterLevelDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
