// Code generated by go-swagger; DO NOT EDIT.

package water_level

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SaveWaterLevelHandlerFunc turns a function with the right signature into a save water level handler
type SaveWaterLevelHandlerFunc func(SaveWaterLevelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SaveWaterLevelHandlerFunc) Handle(params SaveWaterLevelParams) middleware.Responder {
	return fn(params)
}

// SaveWaterLevelHandler interface for that can handle valid save water level params
type SaveWaterLevelHandler interface {
	Handle(SaveWaterLevelParams) middleware.Responder
}

// NewSaveWaterLevel creates a new http.Handler for the save water level operation
func NewSaveWaterLevel(ctx *middleware.Context, handler SaveWaterLevelHandler) *SaveWaterLevel {
	return &SaveWaterLevel{Context: ctx, Handler: handler}
}

/*
	SaveWaterLevel swagger:route POST /water/level Water Level saveWaterLevel

Stores the current water level reading in the database.
*/
type SaveWaterLevel struct {
	Context *middleware.Context
	Handler SaveWaterLevelHandler
}

func (o *SaveWaterLevel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewSaveWaterLevelParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// SaveWaterLevelBody save water level body
//
// swagger:model SaveWaterLevelBody
type SaveWaterLevelBody struct {

	// depth of empty volume in tank.
	EmptyWaterDepth int64 `json:"emptyWaterDepth,omitempty"`
}

// Validate validates this save water level body
func (o *SaveWaterLevelBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this save water level body based on context it is used
func (o *SaveWaterLevelBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SaveWaterLevelBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SaveWaterLevelBody) UnmarshalBinary(b []byte) error {
	var res SaveWaterLevelBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
