// Code generated by go-swagger; DO NOT EDIT.

package water_level_anomaly

import (
	"context"
	stderrors "errors"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"

	"Water-Level-Gauge-er/orchestrator/models"
)

// GetWaterAnomalyHistoryHandlerFunc turns a function with the right signature into a get water anomaly history handler
type GetWaterAnomalyHistoryHandlerFunc func(GetWaterAnomalyHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWaterAnomalyHistoryHandlerFunc) Handle(params GetWaterAnomalyHistoryParams) middleware.Responder {
	return fn(params)
}

// GetWaterAnomalyHistoryHandler interface for that can handle valid get water anomaly history params
type GetWaterAnomalyHistoryHandler interface {
	Handle(GetWaterAnomalyHistoryParams) middleware.Responder
}

// NewGetWaterAnomalyHistory creates a new http.Handler for the get water anomaly history operation
func NewGetWaterAnomalyHistory(ctx *middleware.Context, handler GetWaterAnomalyHistoryHandler) *GetWaterAnomalyHistory {
	return &GetWaterAnomalyHistory{Context: ctx, Handler: handler}
}

/*
	GetWaterAnomalyHistory swagger:route GET /water/anomaly/history Water Level Anomaly getWaterAnomalyHistory

GetWaterAnomalyHistory get water anomaly history API
*/
type GetWaterAnomalyHistory struct {
	Context *middleware.Context
	Handler GetWaterAnomalyHistoryHandler
}

func (o *GetWaterAnomalyHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetWaterAnomalyHistoryParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetWaterAnomalyHistoryOKBody get water anomaly history o k body
//
// swagger:model GetWaterAnomalyHistoryOKBody
type GetWaterAnomalyHistoryOKBody struct {

	// entries
	Entries []*models.WaterLevelAnomaly `json:"Entries"`

	// total number of entries, for pagination
	TotalEntries int64 `json:"TotalEntries,omitempty"`
}

// Validate validates this get water anomaly history o k body
func (o *GetWaterAnomalyHistoryOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEntries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWaterAnomalyHistoryOKBody) validateEntries(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Entries) { // not required
		return nil
	}

	for i := 0; i < len(o.Entries); i++ {
		if typeutils.IsZero(o.Entries[i]) { // not required
			continue
		}

		if o.Entries[i] != nil {
			if err := o.Entries[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getWaterAnomalyHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getWaterAnomalyHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get water anomaly history o k body based on the context it is used
func (o *GetWaterAnomalyHistoryOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateEntries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWaterAnomalyHistoryOKBody) contextValidateEntries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Entries); i++ {

		if o.Entries[i] != nil {

			if typeutils.IsZero(o.Entries[i]) { // not required
				return nil
			}

			if err := o.Entries[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getWaterAnomalyHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getWaterAnomalyHistoryOK" + "." + "Entries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWaterAnomalyHistoryOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWaterAnomalyHistoryOKBody) UnmarshalBinary(b []byte) error {
	var res GetWaterAnomalyHistoryOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
