// Code generated by go-swagger; DO NOT EDIT.

package water_level_anomaly

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetWaterAnomalyHistoryParams creates a new GetWaterAnomalyHistoryParams object
// with the default values initialized.
func NewGetWaterAnomalyHistoryParams() GetWaterAnomalyHistoryParams {

	var (
		// initialize parameters with default values

		itemsPerPageDefault = int64(0)
		pageNumberDefault   = int64(0)
	)

	return GetWaterAnomalyHistoryParams{
		ItemsPerPage: &itemsPerPageDefault,

		PageNumber: &pageNumberDefault,
	}
}

// GetWaterAnomalyHistoryParams contains all the bound params for the get water anomaly history operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetWaterAnomalyHistory
type GetWaterAnomalyHistoryParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*items per page to be fetched
	  In: query
	  Default: 0
	*/
	ItemsPerPage *int64

	/*page number to be fetched
	  In: query
	  Default: 0
	*/
	PageNumber *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWaterAnomalyHistoryParams() beforehand.
func (o *GetWaterAnomalyHistoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qItemsPerPage, qhkItemsPerPage, _ := qs.GetOK("itemsPerPage")
	if err := o.bindItemsPerPage(qItemsPerPage, qhkItemsPerPage, route.Formats); err != nil {
		res = append(res, err)
	}

	qPageNumber, qhkPageNumber, _ := qs.GetOK("pageNumber")
	if err := o.bindPageNumber(qPageNumber, qhkPageNumber, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindItemsPerPage binds and validates parameter ItemsPerPage from query.
func (o *GetWaterAnomalyHistoryParams) bindItemsPerPage(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetWaterAnomalyHistoryParams()
		return nil
	}

	value, err := conv.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("itemsPerPage", "query", "int64", raw)
	}
	o.ItemsPerPage = &value

	return nil
}

// bindPageNumber binds and validates parameter PageNumber from query.
func (o *GetWaterAnomalyHistoryParams) bindPageNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetWaterAnomalyHistoryParams()
		return nil
	}

	value, err := conv.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("pageNumber", "query", "int64", raw)
	}
	o.PageNumber = &value

	return nil
}
