// Code generated by go-swagger; DO NOT EDIT.

package water_level_anomaly

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag/conv"
)

// GetWaterAnomalyHistoryURL generates an URL for the get water anomaly history operation
type GetWaterAnomalyHistoryURL struct {
	ItemsPerPage *int64
	PageNumber   *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetWaterAnomalyHistoryURL) WithBasePath(bp string) *GetWaterAnomalyHistoryURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetWaterAnomalyHistoryURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetWaterAnomalyHistoryURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/water/anomaly/history"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var itemsPerPageQ string
	if o.ItemsPerPage != nil {
		itemsPerPageQ = conv.FormatInteger(*o.ItemsPerPage)
	}
	if itemsPerPageQ != "" {
		qs.Set("itemsPerPage", itemsPerPageQ)
	}

	var pageNumberQ string
	if o.PageNumber != nil {
		pageNumberQ = conv.FormatInteger(*o.PageNumber)
	}
	if pageNumberQ != "" {
		qs.Set("pageNumber", pageNumberQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetWaterAnomalyHistoryURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetWaterAnomalyHistoryURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetWaterAnomalyHistoryURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetWaterAnomalyHistoryURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetWaterAnomalyHistoryURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetWaterAnomalyHistoryURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
