// Code generated by go-swagger; DO NOT EDIT.

package water_level_anomaly

import (
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/runtime"
)

// GetWaterAnomalyOKCode is the HTTP code returned for type GetWaterAnomalyOK
const GetWaterAnomalyOKCode int = 200

/*
GetWaterAnomalyOK Fetched Water Anomaly successfully

swagger:response getWaterAnomalyOK
*/
type GetWaterAnomalyOK struct {

	/*
	  In: Body
	*/
	Payload *models.WaterLevelAnomaly `json:"body,omitempty"`
}

// NewGetWaterAnomalyOK creates GetWaterAnomalyOK with default headers values
func NewGetWaterAnomalyOK() *GetWaterAnomalyOK {

	return &GetWaterAnomalyOK{}
}

// WithPayload adds the payload to the get water anomaly o k response
func (o *GetWaterAnomalyOK) WithPayload(payload *models.WaterLevelAnomaly) *GetWaterAnomalyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water anomaly o k response
func (o *GetWaterAnomalyOK) SetPayload(payload *models.WaterLevelAnomaly) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterAnomalyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetWaterAnomalyDefault Error encountered

swagger:response getWaterAnomalyDefault
*/
type GetWaterAnomalyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetWaterAnomalyDefault creates GetWaterAnomalyDefault with default headers values
func NewGetWaterAnomalyDefault(code int) *GetWaterAnomalyDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWaterAnomalyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get water anomaly default response
func (o *GetWaterAnomalyDefault) WithStatusCode(code int) *GetWaterAnomalyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get water anomaly default response
func (o *GetWaterAnomalyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get water anomaly default response
func (o *GetWaterAnomalyDefault) WithPayload(payload *models.Error) *GetWaterAnomalyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water anomaly default response
func (o *GetWaterAnomalyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterAnomalyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
