// Code generated by go-swagger; DO NOT EDIT.

package water_level_anomaly

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetWaterAnomalyHandlerFunc turns a function with the right signature into a get water anomaly handler
type GetWaterAnomalyHandlerFunc func(GetWaterAnomalyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWaterAnomalyHandlerFunc) Handle(params GetWaterAnomalyParams) middleware.Responder {
	return fn(params)
}

// GetWaterAnomalyHandler interface for that can handle valid get water anomaly params
type GetWaterAnomalyHandler interface {
	Handle(GetWaterAnomalyParams) middleware.Responder
}

// NewGetWaterAnomaly creates a new http.Handler for the get water anomaly operation
func NewGetWaterAnomaly(ctx *middleware.Context, handler GetWaterAnomalyHandler) *GetWaterAnomaly {
	return &GetWaterAnomaly{Context: ctx, Handler: handler}
}

/*
	GetWaterAnomaly swagger:route GET /water/anomaly Water Level Anomaly getWaterAnomaly

GetWaterAnomaly get water anomaly API
*/
type GetWaterAnomaly struct {
	Context *middleware.Context
	Handler GetWaterAnomalyHandler
}

func (o *GetWaterAnomaly) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetWaterAnomalyParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
