// Code generated by go-swagger; DO NOT EDIT.

package water_level_anomaly

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetWaterAnomalyParams creates a new GetWaterAnomalyParams object
//
// There are no default values defined in the spec.
func NewGetWaterAnomalyParams() GetWaterAnomalyParams {

	return GetWaterAnomalyParams{}
}

// GetWaterAnomalyParams contains all the bound params for the get water anomaly operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetWaterAnomaly
type GetWaterAnomalyParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWaterAnomalyParams() beforehand.
func (o *GetWaterAnomalyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
