// Code generated by go-swagger; DO NOT EDIT.

package water_level_anomaly

import (
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/runtime"
)

// GetWaterAnomalyHistoryOKCode is the HTTP code returned for type GetWaterAnomalyHistoryOK
const GetWaterAnomalyHistoryOKCode int = 200

/*
GetWaterAnomalyHistoryOK Fetched Water Anomaly History successfully

swagger:response getWaterAnomalyHistoryOK
*/
type GetWaterAnomalyHistoryOK struct {

	/*
	  In: Body
	*/
	Payload *GetWaterAnomalyHistoryOKBody `json:"body,omitempty"`
}

// NewGetWaterAnomalyHistoryOK creates GetWaterAnomalyHistoryOK with default headers values
func NewGetWaterAnomalyHistoryOK() *GetWaterAnomalyHistoryOK {

	return &GetWaterAnomalyHistoryOK{}
}

// WithPayload adds the payload to the get water anomaly history o k response
func (o *GetWaterAnomalyHistoryOK) WithPayload(payload *GetWaterAnomalyHistoryOKBody) *GetWaterAnomalyHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water anomaly history o k response
func (o *GetWaterAnomalyHistoryOK) SetPayload(payload *GetWaterAnomalyHistoryOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterAnomalyHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetWaterAnomalyHistoryDefault Error encountered

swagger:response getWaterAnomalyHistoryDefault
*/
type GetWaterAnomalyHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetWaterAnomalyHistoryDefault creates GetWaterAnomalyHistoryDefault with default headers values
func NewGetWaterAnomalyHistoryDefault(code int) *GetWaterAnomalyHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWaterAnomalyHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get water anomaly history default response
func (o *GetWaterAnomalyHistoryDefault) WithStatusCode(code int) *GetWaterAnomalyHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get water anomaly history default response
func (o *GetWaterAnomalyHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get water anomaly history default response
func (o *GetWaterAnomalyHistoryDefault) WithPayload(payload *models.Error) *GetWaterAnomalyHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get water anomaly history default response
func (o *GetWaterAnomalyHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWaterAnomalyHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
