// Code generated by go-swagger; DO NOT EDIT.

package configuration

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigurationHandlerFunc turns a function with the right signature into a get configuration handler
type GetConfigurationHandlerFunc func(GetConfigurationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigurationHandlerFunc) Handle(params GetConfigurationParams) middleware.Responder {
	return fn(params)
}

// GetConfigurationHandler interface for that can handle valid get configuration params
type GetConfigurationHandler interface {
	Handle(GetConfigurationParams) middleware.Responder
}

// NewGetConfiguration creates a new http.Handler for the get configuration operation
func NewGetConfiguration(ctx *middleware.Context, handler GetConfigurationHandler) *GetConfiguration {
	return &GetConfiguration{Context: ctx, Handler: handler}
}

/*
	GetConfiguration swagger:route GET /configuration Configuration getConfiguration

Retrieve static configuration
*/
type GetConfiguration struct {
	Context *middleware.Context
	Handler GetConfigurationHandler
}

func (o *GetConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetConfigurationParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
