// Code generated by go-swagger; DO NOT EDIT.

package configuration

import (
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/runtime"
)

// GetConfigurationOKCode is the HTTP code returned for type GetConfigurationOK
const GetConfigurationOKCode int = 200

/*
GetConfigurationOK Configuration fetched successfully

swagger:response getConfigurationOK
*/
type GetConfigurationOK struct {

	/*
	  In: Body
	*/
	Payload *models.Configuration `json:"body,omitempty"`
}

// NewGetConfigurationOK creates GetConfigurationOK with default headers values
func NewGetConfigurationOK() *GetConfigurationOK {

	return &GetConfigurationOK{}
}

// WithPayload adds the payload to the get configuration o k response
func (o *GetConfigurationOK) WithPayload(payload *models.Configuration) *GetConfigurationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get configuration o k response
func (o *GetConfigurationOK) SetPayload(payload *models.Configuration) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetConfigurationDefault Error encountered

swagger:response getConfigurationDefault
*/
type GetConfigurationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigurationDefault creates GetConfigurationDefault with default headers values
func NewGetConfigurationDefault(code int) *GetConfigurationDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConfigurationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get configuration default response
func (o *GetConfigurationDefault) WithStatusCode(code int) *GetConfigurationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get configuration default response
func (o *GetConfigurationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get configuration default response
func (o *GetConfigurationDefault) WithPayload(payload *models.Error) *GetConfigurationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get configuration default response
func (o *GetConfigurationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigurationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
