// Code generated by go-swagger; DO NOT EDIT.

package configuration

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigurationHandlerFunc turns a function with the right signature into a post configuration handler
type PostConfigurationHandlerFunc func(PostConfigurationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigurationHandlerFunc) Handle(params PostConfigurationParams) middleware.Responder {
	return fn(params)
}

// PostConfigurationHandler interface for that can handle valid post configuration params
type PostConfigurationHandler interface {
	Handle(PostConfigurationParams) middleware.Responder
}

// NewPostConfiguration creates a new http.Handler for the post configuration operation
func NewPostConfiguration(ctx *middleware.Context, handler PostConfigurationHandler) *PostConfiguration {
	return &PostConfiguration{Context: ctx, Handler: handler}
}

/*
	PostConfiguration swagger:route POST /configuration Configuration postConfiguration

Store static configuration
*/
type PostConfiguration struct {
	Context *middleware.Context
	Handler PostConfigurationHandler
}

func (o *PostConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPostConfigurationParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
