// Code generated by go-swagger; DO NOT EDIT.

package configuration

import (
	stderrors "errors"
	"io"
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"
)

// NewPostConfigurationParams creates a new PostConfigurationParams object
//
// There are no default values defined in the spec.
func NewPostConfigurationParams() PostConfigurationParams {

	return PostConfigurationParams{}
}

// PostConfigurationParams contains all the bound params for the post configuration operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostConfiguration
type PostConfigurationParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Configuration *models.Configuration
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostConfigurationParams() beforehand.
func (o *PostConfigurationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer func() {
			_ = r.Body.Close()
		}()
		var body models.Configuration
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if stderrors.Is(err, io.EOF) {
				res = append(res, errors.Required("configuration", "body", ""))
			} else {
				res = append(res, errors.NewParseError("configuration", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Configuration = &body
			}
		}
	} else {
		res = append(res, errors.Required("configuration", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
