// Code generated by go-swagger; DO NOT EDIT.

package configuration

import (
	"net/http"

	"Water-Level-Gauge-er/orchestrator/models"
	"github.com/go-openapi/runtime"
)

// PostConfigurationOKCode is the HTTP code returned for type PostConfigurationOK
const PostConfigurationOKCode int = 200

/*
PostConfigurationOK Configuration stored successfully

swagger:response postConfigurationOK
*/
type PostConfigurationOK struct {
}

// NewPostConfigurationOK creates PostConfigurationOK with default headers values
func NewPostConfigurationOK() *PostConfigurationOK {

	return &PostConfigurationOK{}
}

// WriteResponse to the client
func (o *PostConfigurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
PostConfigurationDefault Error encountered

swagger:response postConfigurationDefault
*/
type PostConfigurationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigurationDefault creates PostConfigurationDefault with default headers values
func NewPostConfigurationDefault(code int) *PostConfigurationDefault {
	if code <= 0 {
		code = 500
	}

	return &PostConfigurationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post configuration default response
func (o *PostConfigurationDefault) WithStatusCode(code int) *PostConfigurationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post configuration default response
func (o *PostConfigurationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post configuration default response
func (o *PostConfigurationDefault) WithPayload(payload *models.Error) *PostConfigurationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post configuration default response
func (o *PostConfigurationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigurationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
